#!/bin/bash

service::config_set() {
  config::check_or_set $1 $2 $SERVICE_CONFIG "${@:3}"
}

check() {
  if [ "$DEBUG" = "true" ]; then
    log::info "[DEBUG][service]: $SERVICE_CONFIG"
    cat $SERVICE_CONFIG
  fi

  service::config_set SERVICE_PAOPAO_CE_COMPANY_NAME text "Company Name:" "zmicro"
  service::config_set SERVICE_PAOPAO_CE_COMPANY_DOMAIN text "Company Domain:"  "zmicro.com"

  service::config_set SERVICE_PAOPAO_CE_SECRET_KEY text "Secret Key:" "$(os::random_string 8)"

  service::config_set SERVICE_PAOPAO_CE_DOREAMON_CLIENT_ID text "Doreamon Client ID:"
  service::config_set SERVICE_PAOPAO_CE_DOREAMON_CLIENT_SECRET text "Doreamon Client Secret:"
  service::config_set SERVICE_PAOPAO_CE_DOREAMON_REDIRECT_URI text "Doreamon Redirect URI:"

  service::config_set SERVICE_PAOPAO_CE_DATABASE_HOST text "Database Host:" postgres
  service::config_set SERVICE_PAOPAO_CE_DATABASE_PORT text "Database Port:" 5432
  service::config_set SERVICE_PAOPAO_CE_DATABASE_USERNAME text "Database Username:" postgres
  service::config_set SERVICE_PAOPAO_CE_DATABASE_PASSWORD text "Database Password:"
  service::config_set SERVICE_PAOPAO_CE_DATABASE_NAME text "Database Name:" paopao_ce

  service::config_set SERVICE_PAOPAO_CE_MEILISEARCH_HOST text "Meilisearch Host:" meilisearch
  service::config_set SERVICE_PAOPAO_CE_MEILISEARCH_PORT text "Meilisearch Port:" 7700
  service::config_set SERVICE_PAOPAO_CE_MEILISEARCH_MASTER_KEY text "Meilisearch Master Key:"

  # if [ ! -f "${SERVICE_PAOPAO_CE_CONFIGS_HOME}/config.yaml" ]; then
  cat ${SERVICE_DIR}/conf/config.yaml.sample |
    sed "s%<SERVICE_PAOPAO_CE_COMPANY_NAME>%${SERVICE_PAOPAO_CE_COMPANY_NAME}%g" |
    sed "s%<SERVICE_PAOPAO_CE_COMPANY_DOMAIN>%${SERVICE_PAOPAO_CE_COMPANY_DOMAIN}%g" |
    sed "s%<SERVICE_PAOPAO_CE_DATABASE_HOST>%${SERVICE_PAOPAO_CE_DATABASE_HOST}%g" |
    sed "s%<SERVICE_PAOPAO_CE_DATABASE_PORT>%${SERVICE_PAOPAO_CE_DATABASE_PORT}%g" |
    sed "s%<SERVICE_PAOPAO_CE_DATABASE_USERNAME>%${SERVICE_PAOPAO_CE_DATABASE_USERNAME}%g" |
    sed "s%<SERVICE_PAOPAO_CE_DATABASE_PASSWORD>%${SERVICE_PAOPAO_CE_DATABASE_PASSWORD}%g" |
    sed "s%<SERVICE_PAOPAO_CE_DATABASE_NAME>%${SERVICE_PAOPAO_CE_DATABASE_NAME}%g" |
    sed "s%<SERVICE_PAOPAO_CE_MEILISEARCH_HOST>%${SERVICE_PAOPAO_CE_MEILISEARCH_HOST}%g" |
    sed "s%<SERVICE_PAOPAO_CE_MEILISEARCH_PORT>%${SERVICE_PAOPAO_CE_MEILISEARCH_PORT}%g" |
    sed "s%<SERVICE_PAOPAO_CE_MEILISEARCH_MASTER_KEY>%${SERVICE_PAOPAO_CE_MEILISEARCH_MASTER_KEY}%g" >${SERVICE_PAOPAO_CE_CONFIGS_HOME}/config.yaml
  # fi
}

check $@
