services:
  paopao-ce:
    restart: always
    image: whatwewant/paopao-ce:${SERVICE_PAOPAO_CE_IMAGE_VERSION}
    # ports:
    #   - 0.0.0.0:${SERVICE_PAOPAO_CE_PORT}:8008
    # environment:
    #   PORT: $SERVICE_PAOPAO_CE_PORT
    #   USERNAME: ${SERVICE_PAOPAO_CE_USERNAME}
    #   PASSWORD: ${SERVICE_PAOPAO_CE_PASSWORD}
    volumes:
      - ${SERVICE_PAOPAO_CE_CONFIGS_HOME}/config.yaml:/app/paopao-ce/config.yaml
      - ${SERVICE_PAOPAO_CE_DATA_HOME}/custom:/app/paopao-ce/custom

  paopao-ce_meili:
    image: whatwewant/meilisearch:v1.4-1
    restart: always
    # ports:
    #   - 7700:7700
    volumes:
      - ${SERVICE_PAOPAO_CE_DATA_HOME}/custom/data/meili/data:/meili_data
    environment:
      - MEILI_MASTER_KEY=paopao-meilisearch
  
  paopao-ce_redis:
    image: whatwewant/redis-stack:v7.2-1
    restart: always
    # ports:
    #   - 6379:6379
    #   - 8001:8001
    environment:
      REDISEARCH_ARGS: "MAXSEARCHRESULTS 5"
      
networks:
  default:
    external: true
    name: compose-ingress
