services:
  paopao-ce:
    restart: always
    image: whatwewant/connect-doreamon:v1
    environment:
      MODE: production
      UPSTREAM: http://paopao-ce_upstream:8008
      SECRET_KEY: ${SERVICE_PAOPAO_CE_SECRET_KEY}
      CLIENT_ID: ${SERVICE_PAOPAO_CE_DOREAMON_CLIENT_ID}
      CLIENT_SECRET: ${SERVICE_PAOPAO_CE_DOREAMON_CLIENT_SECRET}
      REDIRECT_URI: ${SERVICE_PAOPAO_CE_DOREAMON_REDIRECT_URI}
      BACKEND_PREFIX: /v1
      BACKEND_DISABLE_PREFIX_REWRITE: true

  paopao-ce_upstream:
    restart: always
    image: whatwewant/paopao-ce:${SERVICE_PAOPAO_CE_IMAGE_VERSION}
    # ports:
    #   - 0.0.0.0:${SERVICE_PAOPAO_CE_PORT}:8008
    environment:
      SECRET_KEY: ${SERVICE_PAOPAO_CE_SECRET_KEY}
    volumes:
      - ${SERVICE_PAOPAO_CE_CONFIGS_HOME}/config.yaml:/app/paopao-ce/config.yaml
      - ${SERVICE_PAOPAO_CE_DATA_HOME}/paopao-ce:/app/paopao-ce/custom

  paopao-ce_meili:
    image: whatwewant/meilisearch:v1.4-1
    restart: always
    # ports:
    #   - 7700:7700
    volumes:
      - ${SERVICE_PAOPAO_CE_DATA_HOME}/meili:/meili_data
    environment:
      - MEILI_MASTER_KEY=paopao-meilisearch
  
  paopao-ce_redis:
    image: whatwewant/redis-stack:v7.2-1
    restart: always
    # ports:
    #   - 6379:6379
    #   - 8001:8001
    environment:
      REDISEARCH_ARGS: "MAXSEARCHRESULTS 5"
      
networks:
  default:
    external: true
    name: compose-ingress
