services:
  paopao-ce:
    restart: always
    image: whatwewant/connect-doreamon:v1
    environment:
      MODE: production
      UPSTREAM: http://paopao-ce_upstream:8008
      SECRET_KEY: ${SERVICE_PAOPAO_CE_SECRET_KEY}
      CLIENT_ID: ${SERVICE_PAOPAO_CE_DOREAMON_CLIENT_ID}
      CLIENT_SECRET: ${SERVICE_PAOPAO_CE_DOREAMON_CLIENT_SECRET}
      REDIRECT_URI: ${SERVICE_PAOPAO_CE_DOREAMON_REDIRECT_URI}
      BACKEND_PREFIX: /v1
      BACKEND_DISABLE_PREFIX_REWRITE: true

  paopao-ce_upstream:
    restart: always
    image: whatwewant/paopao-ce:${SERVICE_PAOPAO_CE_IMAGE_VERSION}
    platform: linux/amd64
    # ports:
    #   - 0.0.0.0:${SERVICE_PAOPAO_CE_PORT}:8008
    environment:
      SECRET_KEY: ${SERVICE_PAOPAO_CE_SECRET_KEY}
      COMPANY_NAME: ${SERVICE_PAOPAO_CE_COMPANY_NAME}
      COMPANY_DOMAIN: ${SERVICE_PAOPAO_CE_COMPANY_DOMAIN}
      DOREAMON_CLIENT_ID: ${SERVICE_PAOPAO_CE_DOREAMON_CLIENT_ID}
      DOREAMON_CLIENT_SECRET: ${SERVICE_PAOPAO_CE_DOREAMON_CLIENT_SECRET}
      DOREAMON_REDIRECT_URI: ${SERVICE_PAOPAO_CE_DOREAMON_REDIRECT_URI}
      DATABASE_HOST: ${SERVICE_PAOPAO_CE_DATABASE_HOST}
      DATABASE_PORT: ${SERVICE_PAOPAO_CE_DATABASE_PORT}
      DATABASE_USERNAME: ${SERVICE_PAOPAO_CE_DATABASE_USERNAME}
      DATABASE_PASSWORD: ${SERVICE_PAOPAO_CE_DATABASE_PASSWORD}
      DATABASE_NAME: ${SERVICE_PAOPAO_CE_DATABASE_NAME}
      REDIS_HOST: ${SERVICE_PAOPAO_CE_REDIS_HOST}
      REDIS_PORT: ${SERVICE_PAOPAO_CE_REDIS_PORT}
      REDIS_USERNAME: ${SERVICE_PAOPAO_CE_REDIS_USERNAME}
      REDIS_PASSWORD: ${SERVICE_PAOPAO_CE_REDIS_PASSWORD}
      REDIS_DB: ${SERVICE_PAOPAO_CE_REDIS_DB}
      MEILISEARCH_HOST: ${SERVICE_PAOPAO_CE_MEILISEARCH_HOST}
      MEILISEARCH_PORT: ${SERVICE_PAOPAO_CE_MEILISEARCH_PORT}
      MEILISEARCH_MASTER_KEY: ${SERVICE_PAOPAO_CE_MEILISEARCH_MASTER_KEY}
      OSS_ACCESS_KEY_ID: ${SERVICE_PAOPAO_CE_OSS_ACCESS_KEY_ID}
      OSS_ACCESS_KEY_SECRET: ${SERVICE_PAOPAO_CE_OSS_ACCESS_KEY_SECRET}
      OSS_BUCKET: ${SERVICE_PAOPAO_CE_OSS_BUCKET}
      OSS_ENDPOINT: ${SERVICE_PAOPAO_CE_OSS_ENDPOINT}
      OSS_DOMAIN: ${SERVICE_PAOPAO_CE_OSS_DOMAIN}
    volumes:
      # - ${SERVICE_PAOPAO_CE_CONFIGS_HOME}/config.yaml:/app/paopao-ce/config.yaml
      - ${SERVICE_PAOPAO_CE_DATA_HOME}/paopao-ce:/app/paopao-ce/custom
  
  paopao-ce_redis:
    image: whatwewant/redis-stack:v7.2-1
    restart: always
    # ports:
    #   - 6379:6379
    #   - 8001:8001
    environment:
      REDISEARCH_ARGS: "MAXSEARCHRESULTS 5"
      
networks:
  default:
    external: true
    name: compose-ingress
